// <auto-generated />
namespace GameLibrary.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class June30thFixedPublisherData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(June30thFixedPublisherData));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301617091_June30thFixedPublisherData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
